MODEL:
  BACKBONE:
    NAME: "efficientnet"
    COMPOUND_COEF: 3
  DETECTION_HEAD:
    NUM_CLASSES: 1
    ANCHORS_SCALES: (1, 1.6245047927, 2.4966610978)
    ANCHORS_RATIOS: ((0.62, 1.58), (1.0, 1.0), (1.58, 0.62))
INPUT:
  SIZE: (640, 384)
DATASETS:
  TRAIN: ("bdd100k",)
  VAL: ("bdd100k",)
  TEST: ("bdd100k",)
  PREDICT: ("bdd100k",)
DATALOADER:
  BATCH_SIZE: 8
OUTPUT_DIR: "./output/bdd100kcar_pl"
