MODEL:
  DETECTION_ON: True
  BACKBONE:
    NAME: "efficientnet"
    COMPOUND_COEF: 3
  DETECTION_HEAD:
    CATEGORY_LIST: "bdd100k-car"
    ANCHORS_SCALES: (1, 1.6245047927, 2.4966610978)
    ANCHORS_RATIOS: ((0.62, 1.58), (1.0, 1.0), (1.58, 0.62))
INPUT:
  SIZE: (640, 384)
DATASETS:
  TRAIN: ("bdd100k-car",)
  VAL: ("bdd100k-car",)
  TEST: ("bdd100k-car",)
  PREDICT: ("bdd100k-car",)
DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.0001
OUTPUT_DIR: "./output/bdd100k-car"
