MODEL:
  DETECTION_ON: True
  SEGMENTATION_ON: False
  BACKBONE:
    NAME: "efficientnet"
    COMPOUND_COEF: 3
  DETECTION_HEAD:
    NUM_CLASSES: 10
    CATEGORY_LIST: "bdd100k"
    ANCHORS_SCALES: (1, 1.52, 2.14)
    ANCHORS_RATIOS: ((1.0, 1.0), (0.57, 1.82), (1.82, 0.57))
  SEGMENTATION_HEAD:
    NUM_CLASSES: 3
INPUT:
  SIZE: (640, 384)
DATASETS:
  TRAIN: ("bdd100k",)
  VAL: ("bdd100k",)
  TEST: ("bdd100k",)
  PREDICT: ("bdd100k",)
DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.0001
OUTPUT_DIR: "./output/hybridnet_no_resume"
